name: Event Booking App CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Start infrastructure services
      run: |
        cd Backend/tickets
        docker-compose up -d db
        # Wait for database to be ready
        sleep 10

    - name: Run tests
      run: |
        cd Backend/tickets
        mvn clean test
      env:
        DB_PASSWORD: Lakshaya@1008

    - name: Build application
      run: |
        cd Backend/tickets
        mvn clean package -DskipTests

    - name: Stop services
      run: |
        cd Backend/tickets
        docker-compose down

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: jar-artifact
        path: Backend/tickets/target/*.jar
